import type { Metadata } from "next";
import "./globals.css";
import SmoothScroll from '@/components/SmoothScroll'
import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "Satish 🙋‍♂️",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <SmoothScroll />

        <Header/>
        {children}
      </body>
    </html>
  );
}
